// Theme: the original desi theka — Bunty bhai, cricket on the TV, Chhotu the waiter.
import { Scene } from '../scene.js';
import { Friend, Waiter } from '../characters.js';

export default {
  id: 'theka',
  name: 'Desi Theka',
  emoji: '🍺',
  blurb: 'Bunty bhai, cricket on TV & Chhotu the waiter',
  title: ['BHAI KA', 'THEKA'],
  subtitle: 'भाई का ठेका',
  tagline: 'AR beer simulator. Your real hands. Virtual daaru. Zero hangover.',
  enter: 'ENTER THEKA 🍻',
  refillIcon: '🗣️',
  refillStep: 'Out of beer? Shout <em>“WAITER!”</em>',
  help: ['🗣️ “WAITER!” / ✋ hand up', 'Chhotu brings & opens new bottles'],
  createScene: (rs) => new Scene(rs),
  createCast: () => ({ companion: new Friend(), server: new Waiter() }),
  refill: 'waiter',
  slots: [655, 765, 1180, 1295],
  introServe: true,
  introServeDelay: 2,
  voice: {
    who: 'friend',
    serverWho: 'waiter',
    word: 'WAITER',
    wake: /(waiter|waitor|weiter|vetar|veter|wetter|water|bhaiya|bhaiyya|bhaiyaa|chhotu|chotu|chootu|oye|one more|वेटर|भैया|छोटू|ओए)/i,
  },
  tutorial: [
    '✊ Make a FIST on a bottle to pick it up',
    '🍺 Hold it over the JAR and tilt to pour',
    '😮 Grab the JAR and bring it to your MOUTH',
    '🗣️ Out of beer? Shout "WAITER!" (or raise a hand ✋)',
  ],
  prompt: { title: 'BOLO "WAITER!"', sub: '🗣️ shout it   •   ✋ raise a hand   •   ⌨️ press W' },
  callLabels: { voice: 'WAITERRR! 📣', hand: 'OYE CHHOTU! ✋', key: 'WAITER! 🛎️' },
  refillButton: '🛎️ WAITER',
  cheersText: 'CHEERS! 🍻',
  hearts: false,
  jarText: 'JAR KHATAM!',
  proText: 'PRO BEWDA UNLOCKED 🏆',
  music: 'dholak',
  ambience: 'crowd',
  hud: { panel: 'rgba(14,9,4,.68)', border: 'rgba(255,210,80,.55)', accent: '#ffd23f', label: '#e9cf9f' },
  loading: [
    'Fridge se thandi nikal rahe hain…',
    'Chakna garam ho raha hai…',
    'Bunty bhai ko bula rahe hain…',
    'Chhotu ko jagaa rahe hain…',
  ],
  lines: {
    intro: ['Aaja bhai! Aaj ka bill mera. Chhotu, bottle laa!', 'Aa gaya mera sher! Chhotu, thandi laa jaldi!'],
    pour: ['Haan bhar de, bhar de!', 'Tircha pakad, jhaag kam banega!', 'Dheere bhai, dheere...'],
    perfect: ['Kya pour hai! Bartender ban ja tu!', 'Ekdum perfect jhaag!'],
    overflow: ['Arre bas bas! Gir rahi hai!', 'Jhaag hi jhaag kar diya!'],
    spill: ['Oye! Beer mat gira, paap lagega!', 'Table ko pila raha hai kya?', 'Arre nuksaan mat kar bhai!'],
    drink: ['Ek saans mein! Ek saans mein!', 'Chugg chugg chugg!', 'Pee ja bhai, pee ja!'],
    bottleDrink: ['Bottle se hi? Patiala style!', 'Jar kis liye rakha hai bhai?'],
    jarDone: ['Waah! Tu toh legend hai!', 'Ek aur ho jaaye?', 'Ye hui na baat!', 'Purana khiladi hai tu!'],
    cheers: ['Cheers bhai! Dosti zindabad!', 'Yaari ke naam!', 'Cheers! Tu mera bhai hai!'],
    empty: ['Khatam! Zor se bol WAITER!', 'Sab khaali... bula WAITER ko!', 'Beer khatam! WAITER ko awaaz de!'],
    callWaiter: ['Haan bula usko!', 'Chhotu! Do aur thandi!'],
    waiterBusy: ['Aa raha hai bhai, sabar kar!'],
    broke: ['Tod di?! Bill mein judega!', 'Arre bottle tod di! Paise tere!'],
    idle: ['Soch kya raha hai? Utha bottle!', 'Beer garam ho jaayegi bhai!', 'Haath mein bottle pakad na!'],
    tipsy: ['Bhai tu hil kyun raha hai?', 'Tu mera sabse accha dost hai... sach mein!', 'Ghar kaise jaayega re?', 'Ek aur... phir pakka ghar.'],
    six: ['SIX! Kya maara!', 'Chhakka! Waah!'],
    four: ['Chauka! Shabaash!'],
    out: ['Out?! Kya bakwaas shot tha!'],
  },
  serverLines: {
    hi: ['Aaya saab!', 'Haan saab, abhi laaya!'],
    full: ['Saab abhi toh bhari padi hai!'],
    bye: ['Enjoy karo saab!', 'Aur kuch chahiye toh bolna!', 'Chakna free hai saab!'],
  },
};
