# Generated by Django 5.2.17 on 2026-09-14 09:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jars', models.PositiveIntegerField(default=0)),
                ('litres_drunk', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('litres_spilled', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('bottles_opened', models.PositiveIntegerField(default=0)),
                ('peak_drunk', models.DecimalField(decimal_places=2, default=0, help_text='Highest talli-meter value reached (0–1.3).', max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='game_gamese_user_id_c1faf8_idx'), models.Index(fields=['-jars'], name='game_gamese_jars_646327_idx')],
            },
        ),
    ]
